namespace platform.tests;

public static class ApiTestsData
{
    internal static Route[] RoutesResponse = new Route[] 
    { 
        new Route {_id="1",active=true},
        new Route {_id="110",active=true},
        new Route {_id="111",active=true},
        new Route {_id="112",active=true},
        new Route {_id="113",active=true},
        new Route {_id="114",active=true},
        new Route {_id="115",active=true},
        new Route {_id="12",active=true},
        new Route {_id="120",active=true},
        new Route {_id="121",active=true},
        new Route {_id="12e",active=true},
        new Route {_id="13",active=true},
        new Route {_id="130",active=true},
        new Route {_id="14",active=true},
        new Route {_id="145",active=true},
        new Route {_id="150",active=true},
        new Route {_id="154",active=true},
        new Route {_id="160",active=true},
        new Route {_id="17",active=true},
        new Route {_id="170",active=true},
        new Route {_id="17e",active=true},
        new Route {_id="18",active=true},
        new Route {_id="18e",active=true},
        new Route {_id="19",active=true},
        new Route {_id="19e",active=true},
        new Route {_id="2",active=true},
        new Route {_id="2+",active=true},
        new Route {_id="20",active=true},
        new Route {_id="200",active=true},
        new Route {_id="201",active=true},
        new Route {_id="202",active=true},
        new Route {_id="203",active=true},
        new Route {_id="204",active=true},
        new Route {_id="206",active=true},
        new Route {_id="21",active=true},
        new Route {_id="210",active=true},
        new Route {_id="22",active=true},
        new Route {_id="22+",active=true},
        new Route {_id="220",active=true},
        new Route {_id="226",active=true},
        new Route {_id="23",active=true},
        new Route {_id="230",active=true},
        new Route {_id="236",active=true},
        new Route {_id="23e",active=true},
        new Route {_id="23z",active=true},
        new Route {_id="24",active=true},
        new Route {_id="25",active=true},
        new Route {_id="250",active=true},
        new Route {_id="251",active=true},
        new Route {_id="26",active=true},
        new Route {_id="260",active=true},
        new Route {_id="261",active=true},
        new Route {_id="262",active=true},
        new Route {_id="264",active=true},
        new Route {_id="27",active=true},
        new Route {_id="28",active=true},
        new Route {_id="280",active=true},
        new Route {_id="281",active=true},
        new Route {_id="29",active=true},
        new Route {_id="290",active=true},
        new Route {_id="29e",active=true},
        new Route {_id="3",active=true},
        new Route {_id="300",active=true},
        new Route {_id="30x",active=true},
        new Route {_id="31x",active=true},
        new Route {_id="32x",active=true},
        new Route {_id="33",active=true},
        new Route {_id="34",active=true},
        new Route {_id="35",active=true},
        new Route {_id="36",active=true},
        new Route {_id="36a",active=true},
        new Route {_id="37",active=true},
        new Route {_id="3a",active=true},
        new Route {_id="52",active=true},
        new Route {_id="56",active=true},
        new Route {_id="57",active=true},
        new Route {_id="58",active=true},
        new Route {_id="60",active=true},
        new Route {_id="60e",active=true},
        new Route {_id="611a",active=true},
        new Route {_id="613a",active=true},
        new Route {_id="614",active=true},
        new Route {_id="614a",active=true},
        new Route {_id="615",active=true},
        new Route {_id="615a",active=true},
        new Route {_id="7",active=true},
        new Route {_id="704a",active=true},
        new Route {_id="711",active=true},
        new Route {_id="711a",active=true},
        new Route {_id="724",active=true},
        new Route {_id="724a",active=true},
        new Route {_id="737",active=true},
        new Route {_id="737a",active=true},
        new Route {_id="739",active=true},
        new Route {_id="739a",active=true},
        new Route {_id="740",active=true},
        new Route {_id="740a",active=true},
        new Route {_id="745",active=true},
        new Route {_id="745a",active=true},
        new Route {_id="751",active=true},
        new Route {_id="751a",active=true},
        new Route {_id="764a",active=true},
        new Route {_id="768",active=true},
        new Route {_id="768a",active=true},
        new Route {_id="769a",active=true},
        new Route {_id="81",active=true},
        new Route {_id="83",active=true},
        new Route {_id="84",active=true},
        new Route {_id="85x",active=true},
        new Route {_id="E1",active=true},
        new Route {_id="E12",active=true},
        new Route {_id="E2",active=true},
        new Route {_id="E3",active=true},
        new Route {_id="E83",active=true},
        new Route {_id="N1",active=true},
        new Route {_id="N2",active=true},
        new Route {_id="N22",active=true},
        new Route {_id="N3",active=true},
        new Route {_id="N4",active=true},
        new Route {_id="N5",active=true},
        new Route {_id="N6",active=true},
        new Route {_id="N66",active=true},
        new Route {_id="N8",active=true},
        new Route {_id="N88",active=true}
    };
    internal static string SetRoutesResponse = "";
    internal static Emissions[] GetDataByDayFullFleetResponse = new Emissions[] { };
    internal static string GetDataByDayElectricFleetResponse = "";
    internal static string GetDataByDayElectricAndEuro6FleetResponse = "";
    internal static string GetDataByDayEuro3AndEuro4AndEuro5AndEuro6FleetResponse = "";
}